VIDEO_SOURCE: ./videos/test.mp4
PROH_AREAS: 
LOG_PATH: ./logs
LOG_FILENAME: logs.log
QUEUE_MAX_SIZE: 300
DETECTOR_CFG_PATH: tracking/det_cfg.yaml
TRACKER_CFG_PATH: tracking/track_cfg.yaml
WINDOW_NAME: Video
BOXES_COLOR: (255, 0, 0) # BGR
BOXES_THICKNESS: 2
ALARM_TIME: 3 # sec
