video_source: ./videos/test.mp4
LOG_PATH: ./logs
LOG_FILENAME: logs.log
QUEUE_MAX_SIZE: 300
DETECTOR_CFG_PATH: tracking/cfg_inference.yaml
WINDOW_NAME: Video
BOXES_COLOR: (255, 0, 0) # BGR
BOXES_THICKNESS: 2
ALARM_TIME: 3 # sec
